import config from "../config";

export const apisEndpoint = {
  loginURL: `${config.LOGIN_BASE_URL}/api/login`,
  activeUserURL: `${config.BASE_URL}/api/GetDailyActiveUsers`,
  getPostURL:`${config.BASE_URL}/api/getPosts`,
  addPostURL: `${config.BASE_URL}/api/newPost`,
  deletePostURL: `${config.BASE_URL}/api/deletePost`,
  singlePostURL:`${config.BASE_URL}/api/getPost`,
  updatePostURL: `${config.BASE_URL}/api/updatePost`,
  getFleetsURL: `${config.BASE_URL_2}/Test-A01/GetAliases`,
  updateFleetsURL : `${config.BASE_URL_2}/Test-A01/StartFleets`,
  allUsersURL: `${config.BASE_URL}/api/getUsersList`,
  userJourneyURL: `${config.BASE_URL}/api/events/`,
  virtaulStorePurchaseURL: `${config.BASE_URL}/api/getVirtualPurchases`,
  getSessionURL: `${config.BASE_URL}/api/averageSessionLength`,
  getUserCountURL: `${config.BASE_URL}/api/getUsersCount`,
  storePurchaseURL: `${config.BASE_URL}/api/getPurchases`,
  roomInfoURL: `${config.BASE_URL}/api/GetRoomsInfo`,
  specificUserDetailURL: `${config.BASE_URL}/api/users`,
  getRetentionURL: `${config.BASE_URL}/api/retention`,
  getDownloadsURL: `${config.BASE_URL}/api/retention`,
  getLauncherAndZoaverseDetailURL:`${config.BASE_URL}/acquisition/firstLaunchStats`,
  getLauncherInstallDetailsURL:`${config.BASE_URL}/acquisition/installStats`,
  getPuchaseRateURL:`${config.BASE_URL}/acquisition/purchaseRate`,
  getTotalDownloadsURL:`${config.BASE_URL}/acquisition/downloadsStats`,
  getActiveUsersCurrentWeekURL:`${config.BASE_URL}/api/active-users/current-week`,
  getAverageSessionsLengthURL:`${config.BASE_URL}/api/averageSessionLength`,
  getReactivationRateURL:`${config.BASE_URL}/api/reactivation-rate/events`,
  getChurnRateURL:`${config.BASE_URL}/api/churn-rate/events`,
  getrepeatPurchaseRateURL: `${config.BASE_URL}/acquisition/repeatPurchaseRate`,
  getUTMInfoURL:`${config.BASE_URL}/awareness/getUtmInfo`,
  getFirstSessionRateRegisteredAccountsURL:`${config.BASE_URL}/api/firstSessionRateRegisteredAccounts`,
  getFirstSessionRateInstallURL:`${config.BASE_URL}/api/firstSessionRateInstall`,
  getTimeToFirstSessionURL:`${config.BASE_URL}/api/timeToFirstSession`,

};
